name: learnladderfaculity
description: A new Flutter project.
version: 1.0.1+4
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  get_storage:
  flutter_svg: ^2.0.9
  get: ^4.6.6
  shared_preferences: ^2.2.2
  textfield_search: ^0.11.1
  connectivity_plus: ^5.0.2
  firebase_core:
  firebase_messaging:
  intl:
  flutter_html:
  table_calendar:
  image_picker: ^1.0.7
  flutter_file_downloader: ^1.2.1
  url_launcher:
  path_provider :
  awesome_notifications:
  visibility_detector:
  lottie:
  custom_searchable_dropdown: ^2.1.1
  html_editor_enhanced: ^2.5.1
  advanced_datatable: ^0.0.9
  fluttertoast:
  open_filex:
  dio:
  file_picker:
  pdf: ^3.11.1
  share_plus:
  socket_io_client: ^1.0.0
  emoji_picker_flutter:
  laravel_echo:
  badges: ^3.1.2
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  fl_chart: ^0.36.1
  syncfusion_flutter_charts: ^23.1.43
  settings_ui: ^2.0.2

#  laravel_echo_null:


dev_dependencies: 
  flutter_test: 
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
    image_path_android: "assets/projectImages/student.png"
    image_path_ios: "assets/projectImages/student.png"
    android: true
    ios: true
    remove_alpha_ios: true
    adaptive_icon_background: "assets/projectImages/student.png"
    adaptive_icon_foreground: "assets/projectImages/student.png"
    adaptive_icon_monochrome: "assets/projectImages/student.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "path/to/image.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "path/to/image.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "path/to/image.png"

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/projectImages/
    - assets/icons/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Open Sans
      fonts: 
#        - asset: assets/fonts/OpenSansSemibold.ttf
#          weight: 600
        - asset: assets/fonts/OpenSans.ttf
          weight: 400
        - asset: assets/fonts/OpenSansLight.ttf
          weight: 300
        - asset: assets/fonts/OpenSansExtrabold.ttf
          weight: 800
#        - asset: assets/fonts/OpenSansSemiBold.ttf
#          weight: 600
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
