name: learnladder
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  get_storage :
  flutter_svg: ^2.0.9
  get: ^4.6.6
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  firebase_core:
  firebase_messaging:
  intl: ^0.18.0
  flutter_html:
  table_calendar:
  image_picker: ^1.0.7
  flutter_file_downloader: ^1.2.1
  url_launcher: ^6.2.6
  open_file:
  path_provider :
  awesome_notifications:
  visibility_detector: ^0.4.0+2
  lottie: ^3.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/projectImages/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Open Sans
      fonts: 
#        - asset: assets/fonts/OpenSansSemibold.ttf
#          weight: 600
        - asset: assets/fonts/OpenSans.ttf
          weight: 400
        - asset: assets/fonts/OpenSansLight.ttf
          weight: 300
        - asset: assets/fonts/OpenSansExtrabold.ttf
          weight: 800
#        - asset: assets/fonts/OpenSansSemiBold.ttf
#          weight: 600
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
